version: "3.7"
services:
  ##############################################################
  ###  postgres/pgadmin:
  ##############################################################
  postgres:
    container_name: postgres-prod
    image: postgres:14-alpine
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ims
    volumes:
      - /c/Users/s.mbarki/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-prod
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: s.mbarki@isygoit.eu
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  postgres-data: