version: "3.7"
services:
  ##############################################################
  ###  minio:
  ##############################################################
  minio:
    container_name: minIo-prod
    image: bitnami/minio:latest
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /home/prm/prod/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=isygoit.eu