-- Connect to default database
\c
postgres

-- Create schemas
CREATE SCHEMA IF NOT EXISTS kms;
CREATE SCHEMA IF NOT EXISTS ims;
CREATE SCHEMA IF NOT EXISTS dms;
CREATE SCHEMA IF NOT EXISTS sms;
CREATE SCHEMA IF NOT EXISTS mms;
CREATE SCHEMA IF NOT EXISTS cms;
CREATE SCHEMA IF NOT EXISTS hrm;
CREATE SCHEMA IF NOT EXISTS rpm;
CREATE SCHEMA IF NOT EXISTS link;
CREATE SCHEMA IF NOT EXISTS smekit;
CREATE SCHEMA IF NOT EXISTS quiz;