-- Connect to default database
\c postgres

-- Create schemas
CREATE SCHEMA IF NOT EXISTS kms;
CREATE SCHEMA IF NOT EXISTS ims;
CREATE SCHEMA IF NOT EXISTS dms;
CREATE SCHEMA IF NOT EXISTS sms;
CREATE SCHEMA IF NOT EXISTS mms;
CREATE SCHEMA IF NOT EXISTS cms;