version: '3.8'

services:
  config-service:
    container_name: config-service
    image: ${CONFIG_IMAGE}
    ports:
      - "${CONFIG_PORT}:${CONFIG_PORT}"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-service:8088/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 20
    volumes:
      - /c/docker/volumes/cloud/config-data:/config:ro
    networks:
      - cloud-net

  discovery-service:
    container_name: discovery-service
    image: ${DISCOVERY_IMAGE}
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "${DISCOVERY_PORT}:${DISCOVERY_PORT}"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-service:8061/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 20
    volumes:
      - /c/docker/volumes/cloud/discovery-data:/discovery:ro
    networks:
      - cloud-net

  gateway-service:
    container_name: gateway-service
    image: ${GATEWAY_IMAGE}
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://gateway-service:8060/actuator/health" ]
      interval: 10s
      timeout: 3s
      retries: 20
    volumes:
      - /c/docker/volumes/cloud/gateway-data:/gateway:ro
    networks:
      - cloud-net

volumes:
  config-data:
  discovery-data:
  gateway-data:

networks:
  cloud-net:
    driver: bridge