version: "3.7"
services:
  ##############################################################
  ###  postgres/pgadmin:
  ##############################################################
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data  # corrigé chemin volume
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - tools-net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: s.mbarki@isygoit.eu
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - tools-net

volumes:
  postgres-data:
  pgadmin-data:

networks:
  tools-net:
    driver: bridge