version: "3.7"
services:
  ##############################################################
  ###  Backend services:
  ##############################################################
  key-service:
    image: core/kms-serv:latest
    container_name: key-service
    restart: always
    ports:
      - "40403:40403"
    healthcheck:
      test: ls -la
      interval: 4s
      timeout: 2s
      retries: 3
    volumes:
      - /c/docker/volumes/core/kms-data/uploads:/uploads
      #- /c/docker/volumes/core/kms-data/camel:/camel
    networks:
      - core-net
      - cloud_cloud-net
      - tools_tools-net
  ##############################################################
  identity-service:
    image: core/ims-serv:latest
    container_name: identity-service
    restart: always
    ports:
      - "40402:40402"
    depends_on:
      key-service:
        condition: service_healthy
    links:
      - key-service
    volumes:
      - /c/docker/volumes/core/ims-data/uploads:/uploads
      #- /c/docker/volumes/core/kms-data/camel:/camel
    networks:
      - core-net
      - cloud_cloud-net
      - tools_tools-net
  ##############################################################
  messaging-service:
    image: core/mms-serv:latest
    container_name: messaging-service
    restart: always
    ports:
      - "40404:40404"
    depends_on:
      key-service:
        condition: service_healthy
    links:
      - key-service
    volumes:
      - /c/docker/volumes/core/mms-data/uploads:/uploads
      #- /c/docker/volumes/core/kms-data/camel:/camel
    networks:
      - core-net
      - cloud_cloud-net
      - tools_tools-net
  ##############################################################
  document-service:
    image: core/dms-serv:latest
    container_name: document-service
    restart: always
    ports:
      - "40405:40405"
    depends_on:
      key-service:
        condition: service_healthy
    links:
      - key-service
    volumes:
      - /c/docker/volumes/core/dms-data/uploads:/uploads
      #- /c/docker/volumes/core/kms-data/camel:/camel
    networks:
      - core-net
      - cloud_cloud-net
      - tools_tools-net
  ##############################################################
  storage-service:
    image: core/sms-serv:latest
    container_name: storage-service
    restart: always
    ports:
      - "40400:40400"
    depends_on:
      key-service:
        condition: service_healthy
    links:
      - key-service
    volumes:
      - /c/docker/volumes/core/sms-data/uploads:/uploads
      #- /c/docker/volumes/core/kms-data/camel:/camel
    networks:
      - core-net
      - cloud_cloud-net
      - tools_tools-net
  ##############################################################
  calendar-service:
    image: core/cms-serv:latest
    container_name: calendar-service
    restart: always
    ports:
      - "40407:40407"
    depends_on:
      key-service:
        condition: service_healthy
    links:
      - key-service
    volumes:
      - /c/docker/volumes/core/cms-data/uploads:/uploads
      #- /c/docker/volumes/core/kms-data/camel:/camel
    networks:
      - core-net
      - cloud_cloud-net
      - tools_tools-net
  ##############################################################
networks:
  core-net:
    driver: bridge
  cloud_cloud-net:
    external: true
  tools_tools-net:
    external: true