version: "3.7"
services:
  ##############################################################
  ###  Backend services:
  ##############################################################
  config-service:
    image: dhub.prm.isygoit.eu/webapp/backend/config:prod
    container_name: config-prod
    restart: always
    ports:
      - "8088:8088"
    healthcheck:
      test: ls -la
      interval: 4s
      timeout: 2s
      retries: 3
    networks:
      - cloud-prod
      - prm-be-prod
    dns:
      - 127.0.0.11
  ##############################################################
  discovery-service:
    image: dhub.prm.isygoit.eu/webapp/backend/discovery:prod
    container_name: discovery-prod
    restart: always
    ports:
      - "8061:8061"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    healthcheck:
      test: ls -la
      interval: 4s
      timeout: 2s
      retries: 3
    networks:
      - cloud-prod
      - prm-be-prod
    dns:
      - 127.0.0.11
    ##############################################################
  gateway-service:
    image: dhub.prm.isygoit.eu/webapp/backend/gateway:prod
    container_name: gateway-prod
    restart: always
    ports:
      - "8060:8060"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
    healthcheck:
      test: ls -la
      interval: 4s
      timeout: 2s
      retries: 3
    networks:
      - cloud-prod
      - prm-be-prod
    dns:
      - 127.0.0.11
    ##############################################################
    ###  Networks:
    ##############################################################
networks:
  tp-tools:
    name: net-tp-tools
    driver: bridge
  cloud-prod:
    name: net-cloud-prod
    driver: bridge
  prm-fe-prod:
    name: net-prm-fe-prod
    driver: bridge
  prm-be-prod:
    name: net-prm-be-prod
    driver: bridge