version: "3.7"
services:
  scui-fe-dev-local-service:
    image: dhub.dev.prm.isygoit.eu/webapp/frontend/scui:dev-local
    container_name: scui-fe-dev-local
    restart: always
    ports:
      - "4008:4008"
    networks:
      - ai-fe-dev
      - prm-be-dev

  scui-fe-qa-service:
    image: dhub.dev.prm.isygoit.eu/webapp/frontend/scui:docker
    container_name: scui-fe-qa
    restart: always
    ports:
      - "4009:4008"
    networks:
      - ai-fe-dev
      - prm-be-dev
    ##############################################################
    ###  Networks:
    ##############################################################
networks:
  tp-tools:
    name: net-tp-tools
    driver: bridge
  cloud-dev:
    name: net-cloud-dev
    driver: bridge
  prm-fe-dev:
    name: net-prm-fe-dev
    driver: bridge
  prm-be-dev:
    name: net-prm-be-dev
    driver: bridge
  ai-fe-dev:
    name: net-ai-fe-dev
    driver: bridge