version: "3.7"
services:
  ##############################################################
  ###  MMS-Backend service:
  ##############################################################
  messaging-service:
    image: core/mms-serv:latest
    container_name: messaging-service
    restart: always
    ports:
      - "40404:40404"
    volumes:
      - /c/docker/volumes/core/mms-data/uploads:/uploads
      #- /c/docker/volumes/core/kms-data/camel:/camel
    networks:
      - core-net
      - cloud_cloud-net
      - tools_tools-net
  ##############################################################
networks:
  core-net:
    driver: bridge
  cloud_cloud-net:
    external: true
  tools_tools-net:
    external: true